### ISSUE TITLE
코드 리뷰입니다!

### ISSUE THREAD

**Issue by hyun1024** [j-i-s-o-o/inno-spring-lv2#3]
Service의 메소드들이 수행 될 때 throws해 놓은 IllegalArgumentException을 핸들링 하는 방법을 찾아보시는 것도 좋을 것 같아요!

User entity의 username 필드에 unique가 걸려 있지 않아서 username의 중복이 발생할 수 있을 것 같아요! username의 경우 게시글의 수정/삭제 권한을 판별하는 주요한 필드라서 Service의 메서드로 중복을 거를 수 있더라도 unique를 걸어주시면 더 좋을 것 같습니다!

**Comment by j-i-s-o-o** [comment]
감사합니다!
